<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/18 12:03:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=ohrmKevin',
  'username' => 'orangehrmKevin',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
